/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ["./public/index.html", "./public/app.js"],
  safelist: [
    'bg-rose-400',
    'opacity-50',
    'line-through',
    'border-2',
    'border-rose-500',
    'hover:bg-rose-500',
    'text-white',
    'rounded',
    'w-6',
    'h-6',
    'ml-auto',
    'transform',
    'hover:-translate-y-1',
    'hover:shadow-lg',
    'sr-only',
    'bg-white',
    'transition',
    'bg-transparent',
    'border-gray-300',
    'task-checkbox',
    'hover:scale-105',
    'focus:ring-2',
    'focus:ring-rose-400',
    'focus:border-transparent',
    'backdrop-blur-sm',
    'bg-gradient-to-br',
    'from-rose-50',
    'to-white',
    'dark:from-gray-900',
    'dark:to-gray-800',
    'bg-gradient-to-r',
    'from-rose-200',
    'via-rose-300',
    'to-rose-400',
    'bg-opacity-60',
    'text-4xl',
    'font-bold',
    'text-rose-800',
    'dark:text-rose-200',
    'mb-2',
    'text-sm',
    'text-rose-600',
    'dark:text-rose-300',
    'mb-4',
    'rounded-full',
    'hover:bg-gray-100',
    'transform',
    'hover:scale-105',
    'bg-gradient-to-b',
    'from-rose-100',
    'to-rose-200',
    'dark:from-gray-700',
    'dark:to-gray-600',
    'w-72',
    'text-xl',
    'mb-6',
    'space-y-4',
    'p-3',
    'rounded-xl',
    'hover:bg-rose-300',
    'dark:hover:bg-gray-500',
    'transform',
    'hover:scale-105',
    'shadow-sm',
    'hover:shadow-md',
    'border-transparent',
    'hover:border-rose-400',
    'dark:hover:border-gray-400',
    'gap-3',
    'font-medium',
    'bg-white',
    'dark:bg-gray-800',
    'rounded-2xl',
    'shadow-xl',
    'border-gray-200',
    'dark:border-gray-600',
    'mb-6',
    'p-4',
    'from-rose-50',
    'to-rose-100',
    'dark:from-gray-700',
    'dark:to-gray-600',
    'border-rose-200',
    'dark:border-gray-500',
    'text-2xl',
    'gap-2',
    'px-4',
    'py-2',
    'rounded-lg',
    'border-gray-300',
    'dark:border-gray-500',
    'bg-white',
    'dark:bg-gray-700',
    'focus:ring-2',
    'focus:ring-rose-400',
    'focus:border-transparent',
    'gap-3',
    'px-4',
    'py-2',
    'bg-rose-500',
    'hover:bg-rose-600',
    'transform',
    'hover:scale-105',
    'dark:bg-gray-700',
    'dark:hover:bg-gray-600',
    'bg-gray-200',
    'dark:bg-gray-600',
    'hover:bg-gray-300',
    'dark:hover:bg-gray-500',
    'gap-6',
    'mt-8',
    'p-6',
    'flex-1',
    'text-lg',
    'font-medium',
    'hover:bg-rose-600',
    'dark:bg-gray-700',
    'dark:hover:bg-gray-600',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#3B82F6',
        secondary: '#6366F1',
        accent: '#10B981'
      },
      transitionDuration: {
        DEFAULT: '200ms'
      }
    },
  },
  plugins: [],
}
